/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/character/character-base.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CharacterBase(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/character-base.glb')
  const { actions } = useAnimations(animations, group)
  console.log('actions', actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.hips} />
            <primitive object={nodes.armikhandleL} />
            <primitive object={nodes.pooltarL} />
            <primitive object={nodes.ikhandleL} />
            <primitive object={nodes.armikhandleR} />
            <primitive object={nodes.pooltarR} />
            <primitive object={nodes.ikhandleR} />
            <primitive object={nodes.pooltararmL} />
            <primitive object={nodes.pooltararmR} />
          </group>
          <skinnedMesh name="main_man_body" geometry={nodes.main_man_body.geometry} material={materials.DefaultMaterial} skeleton={nodes.main_man_body.skeleton} position={[0, 0, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/character-base.glb')
